// 定义页面元数据，如标题、描述等
import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import { Toaster } from '@/components/ui/sonner';
import AppProviders from '@/components/providers/app-providers';

import "./globals.css";

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   metadataBase:new URL(process.env.NEXT_PUBLIC_APP_URL),

//   title: "FlowScrape Next.js",
//   description: "Generated by create next app",
//   keywords: ['FlowScrape', 'webscrape', 'workflow']
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider
      afterSignOutUrl={'/sign-in'}
      appearance={{
        elements: {
          formButtonPrimary: 'bg-primary hover:bg-primary/90 text-sm !shadow-none'
        }
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className="{inter.className}">
          <AppProviders>{children}</AppProviders>
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
